### PR TITLE
fixing bug bash bugs

### PR DESCRIPTION
**Pull request by BVasquez07**
Added a 500-character cap on the Bio and a 15-character cap on the user name via the maxlength attribute.

### CODE REVIEW

**Comment by john-royal** [comment]
Have you considered adding these to the schema? If you add these constraints as `.min()` and `.max()` properties on the [user schema](https://github.com/john-royal/csc-456-paw/blob/main/src/data/user.ts), they will be enforced at a repository level rather than only at an input level.

**Comment by BVasquez07** [comment]
> Have you considered adding these to the schema? If you add these constraints as `.min()` and `.max()` properties on the [user schema](https://github.com/john-royal/csc-456-paw/blob/main/src/data/user.ts), they will be enforced at a repository level rather than only at an input level.

Will check over and submit a new PR

**Comment by programmerjoban** [comment]
i checked the code should be good to merge

**Comment by john-royal** [comment]
This looks good to me too, I'm going to merge

**Pull request merged**
